AWSTemplateFormatVersion: 2010-09-09
Description: Plantilla Basica Security Group

# Recursos
Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH to client host
      GroupName: SSHSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-005fc0f236362e99f
      InstanceType: t2.micro
      KeyName: vockey
      SecurityGroupIds: 
        - !Ref SSHSecurityGroup
      Tags:
        - Key: Name
          Value: Ubuntu22Instance
